# 행렬과 행렬연산

## 행렬

**행렬** A는 숫자의 2차원 배열입니다. NumPy를 사용하여 행렬로 계산할 때는 이전과 마찬가지로 배열을 사용하게 됩니다. 행렬의 몇 가지 모양은 아래와 같습니다.

$$
\begin{equation}
A = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] \hspace{1cm} 
B = \left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right] \hspace{1cm}
C = \left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] \hspace{1cm}
D = \left[ \begin{array}{r} 2 \\ 6 \end{array}\right]
\end{equation}
$$

행렬은 행과 열의 개수를 지정하여 행렬의 크기 또는 모양에 대해 이야기하는 것이 일반적입니다. 일반적으로 행의 개수가 먼저 나열됩니다. 이 예제에서 $A$와 $C$는 $2 \times 2$ 행렬이고, $B$는 $2 \times 3$ 행렬이며, $D$는 $ 2 \times 1$ 행렬입니다.  $D$와 같이 열이 1개만 있는 행렬은 일반적으로 **벡터**라고 합니다.

행렬의 개별 항목에 대해서도 이야기할 필요가 있습니다. 이에 대한 일반적인 표기법은 행렬에서 항목의 위치를 나타내기 위해 아래 첨자가 있는 소문자입니다. 따라서 $b_{12}$는 행렬 $B$의 첫 번째 행과 두 번째 열에 있는 0을 나타냅니다. 일반적인 위치에 대해 이야기하는 경우, $a_{ij}$와 같이 아래 첨자 안에 변수를 사용할 수 있습니다.

In [2]:
import numpy as np
import sympy as sp
import scipy.linalg as la

A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4],[-1, -2, 1]])
C = np.array([[-2, 1],[4, 1]])
D = np.array([[2],[6]])

행과 열의 모양과 크기에 대해서는 배열 객체의 일부로 저장되며 **shape**라는 메서드로 액세스할 수 있습니다. %B$가 배열인 경우, **B.shape** 객체는 그 자체로 두 개의 항목이 있는 배열입니다. 첫 번째 항목(**인덱스 0**)은 행의 개수이고 두 번째 항목(**인덱스 1**)은 열의 개수입니다.

In [3]:
print(f"Array B has {B.shape[0]} rows.")
print(f"Array B has {B.shape[1]} columns.")

Array B has 2 rows.
Array B has 3 columns.


## 행렬 연산

행렬에 대해 수행해야 할 세 가지 대수 연산이 있습니다. 정의를 위해 $A$와 $C$가 $m \times n$ 행렬이고, $B$가 $n \times k$ 행렬이며, $c$가 숫자라고 가정해 보겠습니다. 행렬과 숫자를 포함하는 대수를 논의할 때 숫자는 일반적으로 **스칼라**라고 합니다.

1. 모든 형태의 행렬에 스칼라를 곱할 수 있습니다. 그 결과 모든 항목에 해당 스칼라가 곱해집니다. 아래 첨자 표기법을 사용하면 다음과 같이 작성할 수 있습니다.

$$
(cA)_{ij} = ca_{ij}
$$

2. 동일한 모양을 가진 두 행렬을 추가할 수 있습니다. 그 결과 해당되는 모든 항목이 추가됩니다.

$$
(A+C)_{ij} = a_{ij} + c_{ij}
$$

3. 행렬 $A$의 열 수가 행렬 $B$의 행 수와 같으면, 행렬을 $A$, $B$ 순서로 곱할 수 있습니다. 그 결과 행의 개수는 $A$와 같고 열의 개수는 $B$와 같은 새로운 행렬 $AB$가 생성됩니다. $(AB)_{ij}$ 행렬은 $A$의 행 $i$와 $B$의 열 $j$의 행렬을 다음과 같이 조합한 행렬이 됩니다.

$$
(AB)_{ij} = \sum_{k=1}^n a_{ik}b_{kj}
$$

**행렬 곱셈**으로 알려진 마지막 연산은 세 가지 연산 중 가장 복잡하고 직관적이지 않습니다. 이 마지막 공식은 처음 접했을 때 다소 어렵게 느껴질 수 있습니다. 몇 가지 예를 들어 설명해 드리겠습니다.

1. 숫자와 행렬의 곱셈입니다:

$$
\begin{matrix}
3A = 3\left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] 
= \left[ \begin{array}{rr} 3 & 9 \\ 6 & 3 \end{array}\right]
\end{matrix}
$$

2. 모양이 같은 두 행렬의 합계입니다:

$$
\begin{matrix}
A + C = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] + 
\left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] 
= \left[ \begin{array}{rr} -1 & 4 \\ 6 & 2 \end{array}\right]
\end{matrix}
$$

3. 두 행렬의 곱셈입니다:

$$
\begin{matrix}
AB = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
\left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right]
 = \left[ \begin{array}{rrr} 0 & -6 & 7  \\  5 & -2 & 9  \end{array}\right]
 \end{matrix}
$$
 
행렬 곱셈에서 어떤 일이 일어나는지 명확히 하기 위해 두 개의 항목을 자세히 계산해 보겠습니다.

$$
\begin{matrix}
(AB)_{12} & = & 1\times 0 + 3 \times (-2) = -6 \\
(AB)_{23} & = & 2 \times 4 + 1 \times 1 = 9
\end{matrix}
$$

이러한 행렬 연산은 모두 NumPy에 내장되어 있지만 행렬 곱셈의 경우 $\texttt{*}$ 대신 $\texttt{@}$ 기호를 사용해야 합니다.

In [4]:
print(3*A,'\n')
print(A+C,'\n')
print(A@B)

[[3 9]
 [6 3]] 

[[-1  4]
 [ 6  2]] 

[[ 0 -6  7]
 [ 5 -2  9]]


## 행렬 연산의 속성

행렬 곱셈에 대해 몇 가지 일반적인 대수적 성질은 아래와 같습니다. $A$, $B$, $C$를 행렬로, $k$를 스칼라로 가정합니다. 여기서 설명한 연관성 및 특성은 행렬 곱셈에도 적용됩니다.

$$
\begin{equation}
k(A+B) = kA + kB
\end{equation}
$$

$$
\begin{equation}
C(A+B) = CA + CB
\end{equation}
$$

$$
\begin{equation}
A(BC) = (AB)C
\end{equation}
$$

$A$와 $B$가 $3 \times 3$ 행렬인 경우에, $AB = BA$가 성립하지 않는다는 것을 주의해야 합니다.

In [5]:
A = np.random.randint(-5,5,size=(3,3))
B = np.random.randint(-5,5,size=(3,3))

print(A@B)
print('\n')
print(B@A)

[[-30  24  13]
 [  0 -12 -29]
 [-20 -20 -20]]


[[-30  13  17]
 [  0  14 -14]
 [-20  16 -46]]


## 행렬의 전치

유용하게 사용할 수 있는 또 다른 일반적인 아이디어는 행렬 전치입니다. 행렬 $A$의 **전치**는 열이 $A$의 행이 되도록 정의된 또 다른 행렬인 $A^T$입니다. A^T$는 모든 항목의 행 인덱스를 열 인덱스로 간단히 바꾸면 됩니다($a^T_{ij} = a_{ji}$). 두 가지 예제만으로도 이 정의를 명확히 이해할 수 있습니다.

$$
\begin{equation}
A = \left[ \begin{array}{rrr} 5 & 4 & 0 \\ 1 & 8 & 3 \\ 6 & 7 & 2\end{array}\right] \hspace{1cm}
A^T = \left[ \begin{array}{rrr} 5 & 1 & 6 \\ 4 & 8 & 7 \\ 0 & 3 & 2\end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
B = \left[ \begin{array}{rrr} 1 & 2 & 7 & 0 \\ 3 & 1 & 5 & 2 \\ 4 & 9 & 8 & 6\end{array}\right] \hspace{1cm}
B^T = \left[ \begin{array}{rrr} 1 & 3 & 4 \\ 2 & 1 & 9 \\ 7 & 5 & 8 \\ 0 & 2 & 6\end{array}\right] \hspace{1cm}
\end{equation}
$$

NumPy 배열 객체에는 이를 위해 $\texttt{transpose}$라는 메서드가 있습니다.

In [6]:
A = np.array([[5, 4, 0],[1, 8, 3],[6, 7, 2]])

## Note that the tranpose method must be called with (), the same as a function with no arguments.
A_T = A.transpose()

print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


행렬 $A$가 자신의 전치와 같을 때, 행렬은 주 대각선을 가로질러 대칭이 되는 성질을 가집니다. 이러한 이유로 행렬 $A$가 $A = A^T$이면 **대칭** 행렬이라고 합니다. 이와 동등하게 행렬의 모든 행렬 $a_{ij}$에 대해 $a_{ij} = a_{ji}$이면 $A$는 대칭이라고 말할 수 있습니다.  아래 행렬 $P$는 그러한 예시 중 하나입니다.

$$
\begin{equation}
P = \left[ \begin{array}{rrr} 1 & 0 & 6 \\ 0 & 3 & 5 \\ 6 & 5 & -2\end{array}\right] \hspace{1cm}
\end{equation}
$$