# 프로그래밍 실습

## 1장

### 1.1 정수를 입력받아서 합을 계산하는 함수 `calc`를 작성하라.

In [2]:
def calc(n):
    sum = 0
    for i in range(0, n+1):
        sum += i
    return sum

In [3]:
calc(10)

55

### 1.2 다음과 같은 행렬 `A` 와 벡터 `v`를 파이썬으로 정의하고, 이를 출력하는 프로그램을 작성하라.

In [4]:
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([[1], [2], [3]])

print(f"A = {A}")
print(f"v = {v}")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
v = [[1]
 [2]
 [3]]


### 1.3 다음과 같은 행렬과 벡터들의 크기를 출력하는 프로그램을 작성하라.

$$
A = 
\begin{matrix}
\left[\begin{array}{ccc} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{array}\right]
\end{matrix}
,
v = 
\begin{matrix}
\left[\begin{array}{c} 1 \\ 2 \\ 3 \end{array}\right]
\end{matrix}
,
w = \begin{matrix}
\left[\begin{array}{c} 1 & 2 & 3 \end{array}\right]
\end{matrix}
,
B = 
\begin{matrix}
\left[\begin{array}{cc} 1 & 2 & 3\\ 4 & 5 & 6 \end{array}\right]
\end{matrix}
$$

In [5]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"A = {A}")
print(f"A.shape = {A.shape}")

v = np.array([[1], [2], [3]])
print(f"v = {v}")
print(f"v.shape = {v.shape}")

w = np.array([1, 2, 3])
print(f"w = {w}")
print(f"w.shape = {w.shape}")

B = np.array([[1,2,3], [4,5,6]])
print(f"B = {B}")
print(f"B.shape = {B.shape}")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
A.shape = (3, 3)
v = [[1]
 [2]
 [3]]
v.shape = (3, 1)
w = [1 2 3]
w.shape = (3,)
B = [[1 2 3]
 [4 5 6]]
B.shape = (2, 3)


## 2장

### 2.1 $2 \times 3$ 영행렬, 모든 성분이 1인 $2 \times 2$ 행렬, 모든 성분이 3인 $3 \times 2$ 행렬, $2 \times 2$ 단위행렬을 만들어 출력하는 프로그램을 작성하라.

In [6]:
a = np.zeros((2,3))
print(f"a = {a}")

b = np.ones((2,2))
print(f"b = {b}")

c = np.full((3,2),3)
print(f"c = {c}")

d = np.eye(2)
print(f"d = {d}")

a = [[0. 0. 0.]
 [0. 0. 0.]]
b = [[1. 1.]
 [1. 1.]]
c = [[3 3]
 [3 3]
 [3 3]]
d = [[1. 0.]
 [0. 1.]]


### 2.2 가우스-조단 소거법을 수행하는 gauss( )라는 함수를 정의하고, 이 함수를 이용하여 다음 연립선형방정식의 해를 구하라. gauss(A)의 입력으로 주어지는 A는 주어진 연립선형방정 식에 대한 첨가행렬이다.

$$
\begin{matrix}
2x_1 + 2x_2 + 4x_3 & = & 18 \\
x_1 + 3x_2 + 2x_3 & = & 13 \\
3x_1 + x_2 + 3x_3 & = & 14 \\
\end{matrix}
$$

In [7]:
def pprint(msg, A):
    print("---", msg, "---")
    (n,m) = A.shape
    for i in range(0, n):
        line = ""
        for j in range(0, m):
            line += "{0:.2f}".format(A[i,j]) + "\t"
            if j == n-1:
                line += "| "
        print(line)
    print("")
    
def gauss(A):
    (n,m) = A.shape

    for i in range(0, min(n,m)):
        # i번째 열에서 절댓값이 최대인 성분의 행 선택
        maxEl = abs(A[i,i])
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k,i]) > maxEl:
                maxEl = abs(A[k,i])
                maxRow = k

        # 현재 i번째 행과 최댓값을 갖는 행 maxRow의 교환
        for k in range(i, m):
            tmp = A[maxRow,k]
            A[maxRow,k] = A[i,k]
            A[i,k] = tmp

        # 추축성분을 1로 만들기
        piv = A[i,i]
        for k in range(i, m):
            A[i,k] = A[i,k]/piv

        # 현재 i번째 열의 i번째 행을 제외한 모두 성분을 0으로 만들기
        for k in range(0, n):
            if k != i:
                c = A[k,i]/A[i,i]
                for j in range(i, m):
                    if i == j:
                        A[k,j] = 0
                    else:
                        A[k,j] = A[k,j] - c * A[i,j]

        pprint(str(i+1)+"번째 반복", A) # 중간 과정 출력

    # Ax=b의 해 반환
    x = np.zeros(m-1)
    for i in range(0,m-1):
        x[i] = A[i,m-1]
    return x

# 주어진 연립선형방정식에 대한 첨가행렬
A = np.array([[2., 2., 4., 18.], [1., 3., 2., 13.], [3., 1., 3., 14.]])

pprint("주어진 문제", A) # 첨가행렬 출력
x = gauss(A) # 가우스-조단 소거법 적용

# 출력 생성
(n,m) = A.shape
line = "해:\t"
for i in range(0, m-1):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)

--- 주어진 문제 ---
2.00	2.00	4.00	| 18.00	
1.00	3.00	2.00	| 13.00	
3.00	1.00	3.00	| 14.00	

--- 1번째 반복 ---
1.00	0.33	1.00	| 4.67	
0.00	2.67	1.00	| 8.33	
0.00	1.33	2.00	| 8.67	

--- 2번째 반복 ---
1.00	0.00	0.88	| 3.63	
0.00	1.00	0.38	| 3.12	
0.00	0.00	1.50	| 4.50	

--- 3번째 반복 ---
1.00	0.00	0.00	| 1.00	
0.00	1.00	0.00	| 2.00	
0.00	0.00	1.00	| 3.00	

해:	1.00	2.00	3.00	


## 3장

### 3.1 다음 벡터 $v_1$ , $v_2$, $v_3$를 행으로 하는 행렬 A와 열로 하는 행렬 B 를 이들 벡터를 사용하여 만들고, 행렬 $C$ 에 $v_3$를 열로 추가하여 행렬 $D$를 만들어라. 또한 행렬 $E$의 1행 4열의 성분, 2 행 3열의 성분, 1~2 행의 3열에 해당하는 부분행렬, 1~2행의 3~4열에 해당하는 부분행렬, 3행에 해당하는 부분행렬을 출력하라. 마지막으로 행렬 $E$의 1행 1열의 성분을 -1로 변경하고 행렬 $E$를 출력하라.

In [8]:
print("벡터의 결합에 의한 행렬 생성")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

A = np.vstack([v1, v2, v3]) # v1, v2, v3를 각각 행으로 하는 행렬 A 생성
print("A =", A)

B = np.column_stack([v1, v2, v3]) # v1, v2, v3를 각각 열로 하는 행렬 B 생성
print("B =", B)

C = np.array([[1, 2], [3, 4], [5, 6]])
print("C =", C)

D = np.column_stack([C, v3]) # 행렬 C에 v3를 열로 추가하여 행렬 D 생성
print("D =", D)

print("행렬의 성분 접근")
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("E[0,3] =", E[0,3]) # 1행 4열의 성분
print("E[1,2] =", E[1,2]) # 2행 3열의 성분

print("E[0:2, 2] =", E[0:2, 2]) # E의 1~2행의 3열에 해당하는 부분행렬
print("E[0:2, 2:4] =", E[0:2, 2:4]) # E의 1~2행의 3~4열에 해당하는 부분행렬
print("E[2, :] =", E[2, :]) # E의 3행에 해당하는 부분행렬

print("성분의 변경")
print("E =", E)

print("E[0,0] = ", E[0, 0])
E[0, 0] = -1 # E의 1행 1열 성분을 -1로 변경
print(E)
print("E[0,0] = ", E[0, 0])


벡터의 결합에 의한 행렬 생성
A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[1 4 7]
 [2 5 8]
 [3 6 9]]
C = [[1 2]
 [3 4]
 [5 6]]
D = [[1 2 7]
 [3 4 8]
 [5 6 9]]
행렬의 성분 접근
E[0,3] = 4
E[1,2] = 7
E[0:2, 2] = [3 7]
E[0:2, 2:4] = [[3 4]
 [7 8]]
E[2, :] = [ 9 10 11 12]
성분의 변경
E = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  1
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  -1


### 3.2 다음과 같은 행렬과 벡터를 이용하여 $A + B$, $A - B$, $3A$, $2v$, $AB$, $AC$, $Av$, $A^2$, $A^3$, A 와 B 의 대응 성분별 곱셈 $A*B$, A와 B의 대응 성분별 나눗셈 $A/B$, 성분별 거듭제곱 $A**2$, $A^T$ , $v^T$ , 대각행렬 $diag(1, 2, 3)$의 생성, $D_{11}$, $D_{12}$, $D_{21}$, $D_{22}$를 사용한 블록행렬 $D$의 생성 연산을 수행하고 결과를 출력하는 프로그램을 작성하라.

In [10]:
# 행렬 A를 출력하는 함수
def pprint(msg, A):
    print("---", msg, "---")
    (n,m) = A.shape
    for i in range(0, n):
        line = ""
        for j in range(0, m):
            line += "{0:.2f}".format(A[i,j]) + "\t"
        print(line)
    print("")
    
A = np.array([[1., 2.], [3., 4.]])
B = np.array([[2., 2.], [1., 3.]])
C = np.array([[4., 5., 6.], [7., 8., 9.]])
v = np.array([[10.], [20.]])

pprint("A+B", A+B) # 행렬의 합 A+B
pprint("A-B", A-B) # 행렬의 차 A-B

pprint("3*A ", 3*A) # 행렬의 스칼라배 3A
pprint("2*v ", 2*v) # 벡터의 스칼라배 2v

pprint("matmul(A,B)", np.matmul(A,B)) # 행렬의 곱 AB
pprint("matmul(A,C)", np.matmul(A,C)) # 행렬의 곱 AC
pprint("A*v", A*v) # 행렬과 벡터의 곱 Av

pprint("matrix_power(A, 2)", np.linalg.matrix_power(A, 2)) # 행렬의 거듭제곱 A2
pprint("matrix_power(A, 3)", np.linalg.matrix_power(A, 3)) # 행렬의 거듭제곱 A3

pprint("A*B", A*B) # 행렬의 성분별 곱셈 A*B
pprint("A/B", A/B) # 행렬의 성분별 나눗셈 A/B
pprint("A**2 == A*A", A**2) # 행렬의 성분별 거듭제곱 A**2

pprint("A.T", A.T) # 행렬의 전치 AT
pprint("v.T", v.T) # 벡터의 전치 vT

M = np.diag([1, 2, 3]) # 대각행렬 diag(1,2,3) 생성
pprint("diag(1,2,3) =", M)

D11 = np.array([[1, 2], [3, 4]])
D12 = np.array([[5], [6]])
D21 = np.array([[7, 7]])
D22 = np.array([[8]])
D = np.block([[D11, D12], [D21, D22]]) # 블록행렬 D 생성
pprint("block matrix", D)

--- A+B ---
3.00	4.00	
4.00	7.00	

--- A-B ---
-1.00	0.00	
2.00	1.00	

--- 3*A  ---
3.00	6.00	
9.00	12.00	

--- 2*v  ---
20.00	
40.00	

--- matmul(A,B) ---
4.00	8.00	
10.00	18.00	

--- matmul(A,C) ---
18.00	21.00	24.00	
40.00	47.00	54.00	

--- A*v ---
10.00	20.00	
60.00	80.00	

--- matrix_power(A, 2) ---
7.00	10.00	
15.00	22.00	

--- matrix_power(A, 3) ---
37.00	54.00	
81.00	118.00	

--- A*B ---
2.00	4.00	
3.00	12.00	

--- A/B ---
0.50	1.00	
3.00	1.33	

--- A**2 == A*A ---
1.00	4.00	
9.00	16.00	

--- A.T ---
1.00	3.00	
2.00	4.00	

--- v.T ---
10.00	20.00	

--- diag(1,2,3) = ---
1.00	0.00	0.00	
0.00	2.00	0.00	
0.00	0.00	3.00	

--- block matrix ---
1.00	2.00	5.00	
3.00	4.00	6.00	
7.00	7.00	8.00	

