# 프로그래밍 실습

## 1장

### 1.1 정수를 입력받아서 합을 계산하는 함수 `calc`를 작성하라.

In [1]:
def calc(n):
    sum = 0
    for i in range(0, n+1):
        sum += i
    return sum

In [2]:
calc(10)

55

### 1.2 다음과 같은 행렬 `A` 와 벡터 `v`를 파이썬으로 정의하고, 이를 출력하는 프로그램을 작성하라.

In [3]:
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([[1], [2], [3]])

print(f"A = {A}")
print(f"v = {v}")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
v = [[1]
 [2]
 [3]]


### 1.3 다음과 같은 행렬과 벡터들의 크기를 출력하는 프로그램을 작성하라.

$$
A = 
\begin{matrix}
\left[\begin{array}{ccc} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{array}\right]
\end{matrix}
,
v = 
\begin{matrix}
\left[\begin{array}{c} 1 \\ 2 \\ 3 \end{array}\right]
\end{matrix}
,
w = \begin{matrix}
\left[\begin{array}{c} 1 & 2 & 3 \end{array}\right]
\end{matrix}
,
B = 
\begin{matrix}
\left[\begin{array}{cc} 1 & 2 & 3\\ 4 & 5 & 6 \end{array}\right]
\end{matrix}
$$

In [4]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"A = {A}")
print(f"A.shape = {A.shape}")

v = np.array([[1], [2], [3]])
print(f"v = {v}")
print(f"v.shape = {v.shape}")

w = np.array([1, 2, 3])
print(f"w = {w}")
print(f"w.shape = {w.shape}")

B = np.array([[1,2,3], [4,5,6]])
print(f"B = {B}")
print(f"B.shape = {B.shape}")

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
A.shape = (3, 3)
v = [[1]
 [2]
 [3]]
v.shape = (3, 1)
w = [1 2 3]
w.shape = (3,)
B = [[1 2 3]
 [4 5 6]]
B.shape = (2, 3)


## 2장

### 2.1 $2 \times 3$ 영행렬, 모든 성분이 1인 $2 \times 2$ 행렬, 모든 성분이 3인 $3 \times 2$ 행렬, $2 \times 2$ 단위행렬을 만들어 출력하는 프로그램을 작성하라.

In [5]:
a = np.zeros((2,3))
print(f"a = {a}")

b = np.ones((2,2))
print(f"b = {b}")

c = np.full((3,2),3)
print(f"c = {c}")

d = np.eye(2)
print(f"d = {d}")

a = [[0. 0. 0.]
 [0. 0. 0.]]
b = [[1. 1.]
 [1. 1.]]
c = [[3 3]
 [3 3]
 [3 3]]
d = [[1. 0.]
 [0. 1.]]


### 2.2 가우스-조단 소거법을 수행하는 gauss( )라는 함수를 정의하고, 이 함수를 이용하여 다음 연립선형방정식의 해를 구하라. gauss(A)의 입력으로 주어지는 A는 주어진 연립선형방정 식에 대한 첨가행렬이다.

$$
\begin{matrix}
2x_1 + 2x_2 + 4x_3 & = & 18 \\
x_1 + 3x_2 + 2x_3 & = & 13 \\
3x_1 + x_2 + 3x_3 & = & 14 \\
\end{matrix}
$$

In [6]:
def pprint(msg, A):
    print("---", msg, "---")
    (n,m) = A.shape
    for i in range(0, n):
        line = ""
        for j in range(0, m):
            line += "{0:.2f}".format(A[i,j]) + "\t"
            if j == n-1:
                line += "| "
        print(line)
    print("")

In [7]:
def gauss(A):
    (n,m) = A.shape

    for i in range(0, min(n,m)):
        # i번째 열에서 절댓값이 최대인 성분의 행 선택
        maxEl = abs(A[i,i])
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k,i]) > maxEl:
                maxEl = abs(A[k,i])
                maxRow = k

        # 현재 i번째 행과 최댓값을 갖는 행 maxRow의 교환
        for k in range(i, m):
            tmp = A[maxRow,k]
            A[maxRow,k] = A[i,k]
            A[i,k] = tmp

        # 추축성분을 1로 만들기
        piv = A[i,i]
        for k in range(i, m):
            A[i,k] = A[i,k]/piv

        # 현재 i번째 열의 i번째 행을 제외한 모두 성분을 0으로 만들기
        for k in range(0, n):
            if k != i:
                c = A[k,i]/A[i,i]
                for j in range(i, m):
                    if i == j:
                        A[k,j] = 0
                    else:
                        A[k,j] = A[k,j] - c * A[i,j]

        pprint(str(i+1)+"번째 반복", A) # 중간 과정 출력

    # Ax=b의 해 반환
    x = np.zeros(m-1)
    for i in range(0,m-1):
        x[i] = A[i,m-1]
    return x

# 주어진 연립선형방정식에 대한 첨가행렬
A = np.array([[2., 2., 4., 18.], [1., 3., 2., 13.], [3., 1., 3., 14.]])

pprint("주어진 문제", A) # 첨가행렬 출력
x = gauss(A) # 가우스-조단 소거법 적용

# 출력 생성
(n,m) = A.shape
line = "해:\t"
for i in range(0, m-1):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)

--- 주어진 문제 ---
2.00	2.00	4.00	| 18.00	
1.00	3.00	2.00	| 13.00	
3.00	1.00	3.00	| 14.00	

--- 1번째 반복 ---
1.00	0.33	1.00	| 4.67	
0.00	2.67	1.00	| 8.33	
0.00	1.33	2.00	| 8.67	

--- 2번째 반복 ---
1.00	0.00	0.88	| 3.63	
0.00	1.00	0.38	| 3.12	
0.00	0.00	1.50	| 4.50	

--- 3번째 반복 ---
1.00	0.00	0.00	| 1.00	
0.00	1.00	0.00	| 2.00	
0.00	0.00	1.00	| 3.00	

해:	1.00	2.00	3.00	


## 3장

### 3.1 다음 벡터 $v_1$ , $v_2$, $v_3$를 행으로 하는 행렬 A와 열로 하는 행렬 B 를 이들 벡터를 사용하여 만들고, 행렬 $C$ 에 $v_3$를 열로 추가하여 행렬 $D$를 만들어라. 또한 행렬 $E$의 1행 4열의 성분, 2 행 3열의 성분, 1~2 행의 3열에 해당하는 부분행렬, 1~2행의 3~4열에 해당하는 부분행렬, 3행에 해당하는 부분행렬을 출력하라. 마지막으로 행렬 $E$의 1행 1열의 성분을 -1로 변경하고 행렬 $E$를 출력하라.

In [8]:
print("벡터의 결합에 의한 행렬 생성")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

A = np.vstack([v1, v2, v3]) # v1, v2, v3를 각각 행으로 하는 행렬 A 생성
print("A =", A)

B = np.column_stack([v1, v2, v3]) # v1, v2, v3를 각각 열로 하는 행렬 B 생성
print("B =", B)

C = np.array([[1, 2], [3, 4], [5, 6]])
print("C =", C)

D = np.column_stack([C, v3]) # 행렬 C에 v3를 열로 추가하여 행렬 D 생성
print("D =", D)

print("행렬의 성분 접근")
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("E[0,3] =", E[0,3]) # 1행 4열의 성분
print("E[1,2] =", E[1,2]) # 2행 3열의 성분

print("E[0:2, 2] =", E[0:2, 2]) # E의 1~2행의 3열에 해당하는 부분행렬
print("E[0:2, 2:4] =", E[0:2, 2:4]) # E의 1~2행의 3~4열에 해당하는 부분행렬
print("E[2, :] =", E[2, :]) # E의 3행에 해당하는 부분행렬

print("성분의 변경")
print("E =", E)

print("E[0,0] = ", E[0, 0])
E[0, 0] = -1 # E의 1행 1열 성분을 -1로 변경
print(E)
print("E[0,0] = ", E[0, 0])


벡터의 결합에 의한 행렬 생성
A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[1 4 7]
 [2 5 8]
 [3 6 9]]
C = [[1 2]
 [3 4]
 [5 6]]
D = [[1 2 7]
 [3 4 8]
 [5 6 9]]
행렬의 성분 접근
E[0,3] = 4
E[1,2] = 7
E[0:2, 2] = [3 7]
E[0:2, 2:4] = [[3 4]
 [7 8]]
E[2, :] = [ 9 10 11 12]
성분의 변경
E = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  1
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  -1


### 3.2 다음과 같은 행렬과 벡터를 이용하여 $A + B$, $A - B$, $3A$, $2v$, $AB$, $AC$, $Av$, $A^2$, $A^3$, A 와 B 의 대응 성분별 곱셈 $A*B$, A와 B의 대응 성분별 나눗셈 $A/B$, 성분별 거듭제곱 $A**2$, $A^T$ , $v^T$ , 대각행렬 $diag(1, 2, 3)$의 생성, $D_{11}$, $D_{12}$, $D_{21}$, $D_{22}$를 사용한 블록행렬 $D$의 생성 연산을 수행하고 결과를 출력하는 프로그램을 작성하라.

In [9]:
A = np.array([[1., 2.], [3., 4.]])
B = np.array([[2., 2.], [1., 3.]])
C = np.array([[4., 5., 6.], [7., 8., 9.]])
v = np.array([[10.], [20.]])

pprint("A+B", A+B) # 행렬의 합 A+B
pprint("A-B", A-B) # 행렬의 차 A-B

pprint("3*A ", 3*A) # 행렬의 스칼라배 3A
pprint("2*v ", 2*v) # 벡터의 스칼라배 2v

pprint("matmul(A,B)", np.matmul(A,B)) # 행렬의 곱 AB
pprint("matmul(A,C)", np.matmul(A,C)) # 행렬의 곱 AC
pprint("A*v", A*v) # 행렬과 벡터의 곱 Av

pprint("matrix_power(A, 2)", np.linalg.matrix_power(A, 2)) # 행렬의 거듭제곱 A2
pprint("matrix_power(A, 3)", np.linalg.matrix_power(A, 3)) # 행렬의 거듭제곱 A3

pprint("A*B", A*B) # 행렬의 성분별 곱셈 A*B
pprint("A/B", A/B) # 행렬의 성분별 나눗셈 A/B
pprint("A**2 == A*A", A**2) # 행렬의 성분별 거듭제곱 A**2

pprint("A.T", A.T) # 행렬의 전치 AT
pprint("v.T", v.T) # 벡터의 전치 vT

M = np.diag([1, 2, 3]) # 대각행렬 diag(1,2,3) 생성
pprint("diag(1,2,3) =", M)

D11 = np.array([[1, 2], [3, 4]])
D12 = np.array([[5], [6]])
D21 = np.array([[7, 7]])
D22 = np.array([[8]])
D = np.block([[D11, D12], [D21, D22]]) # 블록행렬 D 생성
pprint("block matrix", D)

--- A+B ---
3.00	4.00	
4.00	7.00	

--- A-B ---
-1.00	0.00	
2.00	1.00	

--- 3*A  ---
3.00	6.00	
9.00	12.00	

--- 2*v  ---
20.00	
40.00	

--- matmul(A,B) ---
4.00	8.00	
10.00	18.00	

--- matmul(A,C) ---
18.00	21.00	24.00	
40.00	47.00	54.00	

--- A*v ---
10.00	20.00	
60.00	80.00	

--- matrix_power(A, 2) ---
7.00	10.00	
15.00	22.00	

--- matrix_power(A, 3) ---
37.00	54.00	
81.00	118.00	

--- A*B ---
2.00	4.00	
3.00	12.00	

--- A/B ---
0.50	1.00	
3.00	1.33	

--- A**2 == A*A ---
1.00	4.00	
9.00	16.00	

--- A.T ---
1.00	3.00	
2.00	4.00	

--- v.T ---
10.00	20.00	

--- diag(1,2,3) = ---
1.00	0.00	0.00	
0.00	2.00	0.00	
0.00	0.00	3.00	

--- block matrix ---
1.00	2.00	5.00	
3.00	4.00	6.00	
7.00	7.00	8.00	



## 4장

### 4.1 다음 행렬 A의 역행렬을 구한 다음, 행렬 A와 구한 역행렬의 곱이 단위행렬 I인지 확인하라. 그다음 난수로 3x3 행렬 B를 만들고 그 역행렬을 구한 후，B와 B 의 역행렬을 곱하여 결과를 출력하라. 또한 다음 행렬 C와 D에 대한 행렬방정식 Cx= D의 해를 역행렬을 이용하여 구한 다음, 해가 맞는지 확인하라. 

In [12]:
A = np.array([[1., 2.], [3., 4.]])
pprint("A", A)

Ainv1 = np.linalg.matrix_power(A, -1) # matrix_power( )를 사용한 역행렬 A-1 계산
pprint("linalg.matrix_power(A, -1) => Ainv1", Ainv1)

Ainv2 = np.linalg.inv(A) # inv( )를 사용한 역행렬 A-1 계산
pprint("np.linalg.inv(A) => Ainv2", Ainv2)

pprint("A*Ainv1", np.matmul(A, Ainv1)) # 행렬 A와 역행렬 A-1의 곱
pprint("A*Ainv2", np.matmul(A, Ainv2)) # 행렬 A와 역행렬 A-1의 곱

B = np.random.rand(3,3) # 난수를 이용한 3x3 행렬 B 생성
pprint("B =", B)
Binv = np.linalg.inv(B) # 역행렬 B-1 계산
pprint("Binv =", Binv)
pprint("B*Binv =", np.matmul(B, Binv)) # 행렬 B와 역행렬 B-1의 곱

# CX = D의 해 계산
C = np.array([[5, 3, 2, 1], [6, 2, 4, 5], [7, 4, 1, 3], [4, 3, 5, 2]])
D = np.array([[4], [2], [5], [1]])
x = np.matmul(np.linalg.inv(C), D)
pprint("x", x) # 해 x 출력
pprint("C*x", np.matmul(C, x)) # C*x의 결과가 D와 같은지 확인


--- A ---
1.00	2.00	
3.00	4.00	

--- linalg.matrix_power(A, -1) => Ainv1 ---
-2.00	1.00	
1.50	-0.50	

--- np.linalg.inv(A) => Ainv2 ---
-2.00	1.00	
1.50	-0.50	

--- A*Ainv1 ---
1.00	0.00	
0.00	1.00	

--- A*Ainv2 ---
1.00	0.00	
0.00	1.00	

--- B = ---
0.29	0.40	0.50	
0.55	0.49	0.21	
0.89	0.29	0.99	

--- Binv = ---
-2.66	1.57	1.01	
2.22	1.00	-1.32	
1.73	-1.71	0.50	

--- B*Binv = ---
1.00	-0.00	0.00	
0.00	1.00	-0.00	
0.00	-0.00	1.00	

--- x ---
1.31	
-0.38	
-0.31	
-0.77	

--- C*x ---
4.00	
2.00	
5.00	
1.00	



### 4.2 임의의 크기의 정방행렬 A 를 LU 분해하는 함수 LU(A)를 사용하여 Ax = b의 해를 구하는 프로그램을 작성하라. [프로그래밍 실습 문제 4-1]의 연립선형방정식을 행렬방정식 Ax = b로 간주하고, 작성한 함수로 계수행렬 A 를 LU 분해하여 이 연립선형방정식의 해를 구하라.

In [13]:
#LU 분해 함수
def LU(A):
    (n,m) = A.shape
    L = np.zeros((n,n)) # 행렬 L 초기화
    U = np.zeros((n,n)) # 행렬 U 초기화
    
    # 행렬 L과 U 계산
    for i in range(0, n):
        for j in range(i, n):
            U[i, j] = A[i, j]
            for k in range(0, i):
                U[i, j] = U[i, j] - L[i, k]*U[k, j]
        L[i,i] = 1
        if i < n-1:
            p = i + 1
            for j in range(0,p):
                L[p, j] = A[p, j]
                for k in range(0, j):
                    L[p, j] = L[p, j] - L[p, k]*U[k, j]
                    L[p,j] = L[p,j]/U[j,j]
    return L, U

# LU 분해를 이용한 Ax=b의 해 구하기
def LU_solver(A, b):
    L, U = LU(A)
    n = len(L)
    # Ly=b 계산
    y = np.zeros((n,1))
    for i in range(0,n):
        y[i] = b[i]
        for k in range(0,i):
            y[i] -= y[k]*L[i,k]
    # Ux=y 계산
    x = np.zeros((n,1))
    for i in range(n-1, -1, -1):
        x[i] = y[i]
        if i < n-1:
            for k in range(i+1,n):
                x[i] -= x[k]*U[i,k]
        x[i] = x[i]/float(U[i,i])
    return x

A = np.array([[5, 3, 2, 1], [6, 2, 4, 5], [7, 4, 1, 3], [4, 3, 5, 2]])
b = np.array([[4], [2], [5], [1]])

# 행렬 A의 LU 분해
L, U = LU(A)
pprint("A", A)
pprint("L", L)
pprint("U", U)

# LU 분해를 이용한 Ax=b의 해 구하기
x = LU_solver(A,b)
pprint("x", x)

--- A ---
5.00	3.00	2.00	1.00	
6.00	2.00	4.00	5.00	
7.00	4.00	1.00	3.00	
4.00	3.00	5.00	2.00	

--- L ---
1.00	0.00	0.00	0.00	
6.00	1.00	0.00	0.00	
7.00	1.06	1.00	0.00	
4.00	0.56	-1.15	1.00	

--- U ---
5.00	3.00	2.00	1.00	
0.00	-16.00	-8.00	-1.00	
0.00	0.00	-4.50	-2.94	
0.00	0.00	0.00	-4.81	

--- x ---
-0.06	
1.54	
-0.38	
0.46	



# 5장

## 5.1 임의의 크기의 정방행렬에 대한 행렬식을 계산하는 프로그램을 작성하고, 이를 이용하여 다음 행렬 A의 행렬식을 구하라.

In [1]:
import numpy as np

def get_minor_matrix(A,i,j): # 행렬 A의 i행과 j열을 제거하고 만든 행렬 생성
    n = len(A)
    M = np.zeros((n-1, n-1))
    for a in range(0,n-1):
        k = a if (a < i) else a+1
        for b in range(0, n-1):
            l = b if (b < j) else b+1
            M[a, b] = A[k, l]
    return M

def determinant(M): # 행렬식 계산
    if len(M) == 2: # 2x2 행렬의 행렬식 계산
        return M[0,0]*M[1,1]-M[0,1]*M[1,0]

    detVal = 0
    for c in range(len(M)):
        detVal += ((-1)**c)*M[0,c]*determinant(get_minor_matrix(M,0,c))
    return detVal

A = np.array([[-4, 0, 2, -1, 0], [1, 3, -3, -1, 4], [2, 0, 1, 3, 0],
              [-2, 1, -3, -1, 5], [1, -5, 1, 0, 5]])
print("A = ", A)
print("det(A) = ", determinant(A))


A =  [[-4  0  2 -1  0]
 [ 1  3 -3 -1  4]
 [ 2  0  1  3  0]
 [-2  1 -3 -1  5]
 [ 1 -5  1  0  5]]
det(A) =  -997.0


## 5.2 수반행렬을 이용한 역행렬 계산 방법을 구현하여, 다음 행렬 A의 역행렬을 계산하라.

In [2]:
import numpy as np

def cofactor(A, i, j): # 여인수 계산
    (n,m) = A.shape
    M = np.zeros((n-1, m-1))
    for a in range(0, n-1):
        k = a if (a < i) else a+1
        for b in range(0, m-1):
            l = b if (b < j) else b+1
            M[a,b] = A[k, l]

    return (-1)**(i+j)*np.linalg.det(M)

def inverse_by_adjoint_matrix(A): # 수반행렬을 이용한 A의 역행렬 계산
    detA = np.linalg.det(A) # A의 행렬식 계산
    (n,m) = A.shape
    adjA = np.zeros((n, m))

    for i in range(0,n): # 수반행렬 생성
        for j in range(0, m):
            adjA[j,i] = cofactor(A, i, j)
    if detA != 0.0:
        return (1./detA) * adjA
    else:
        return 0
    
A = np.array([[-4, 0, 2, -1, 0], [1, 3, -3, -1, 4], [2, 0, 1, 3, 0],
              [-2, 1, -3, -1, 5], [1, -5, 1, 0, 5]])
print("A = ", A)

Ainv = inverse_by_adjoint_matrix(A)
print("A inverse = ", Ainv)

A =  [[-4  0  2 -1  0]
 [ 1  3 -3 -1  4]
 [ 2  0  1  3  0]
 [-2  1 -3 -1  5]
 [ 1 -5  1  0  5]]
A inverse =  [[-0.07321966  0.2106319  -0.03610832 -0.24573721  0.0772317 ]
 [ 0.16950853  0.26579739  0.09729188 -0.14343029 -0.06920762]
 [ 0.32397192  0.30090271  0.09127382 -0.35105316  0.11033099]
 [-0.05917753 -0.24072217  0.32698094  0.28084253 -0.08826479]
 [ 0.11935807  0.16349047  0.08625878 -0.02407222  0.09327984]]


## 5.3 크래머 공식을 이용하여 연립선형방정식의 해를 구하는 방법을 구현하여, 다음 연립선형방정식의 해를 구하라.

In [6]:
import numpy as np

def solve_by_cramer(A, B): # 크래머 공식을 이용한 연립선형방정식 AX=B의 풀이
    X = np.zeros(len(B))
    C = np.copy(A)
    for i in range(0, len(B)):
        for j in range(0, len(B)):
            C[j,i] = B[j].item()
            if i>0:
                C[j,i-1] = A[j,i-1]
        X[i] = np.linalg.det(C)/np.linalg.det(A)
    return X

# AX = B의 해
A = np.array([[2,-1,5,1], [3,2,2,-6], [1,3,3,-1], [5,-2,-3,3]])
B = np.array([[-3], [-32], [-47], [49]])
X = solve_by_cramer(A, B)
print("A = ", A)
print("B = ", B)
print("X = ", X)


A =  [[ 2 -1  5  1]
 [ 3  2  2 -6]
 [ 1  3  3 -1]
 [ 5 -2 -3  3]]
B =  [[ -3]
 [-32]
 [-47]
 [ 49]]
X =  [  2. -12.  -4.   1.]


# 6장

## 6.1 다음과 같이 방향과 크기가 주어진 $R^2$ 공간의 두 힘을 결합한 힘의 방향과 크기를 구하라.

In [7]:
import numpy as np

def get_vector(mag, deg): # 주어진 크기와 방향에 대응하는 벡터 생성
    vec = np.zeros(2)
    vec[0] = mag*np.cos(deg*2*np.pi/360)
    vec[1] = mag*np.sin(deg*2*np.pi/360)
    return vec

def get_mag_deg(vec): # 벡터의 크기와 방향 계산
    mag = np.sqrt(vec[0]*vec[0]+vec[1]*vec[1])
    deg = np.arctan(vec[1]/vec[0]) * 360/(2*np.pi)
    return mag, deg

F1 = get_vector(100, 30) # 크기 100N, 방향 30˚인 힘
F2 = get_vector(120, 60) # 크기 120N, 방향 60˚인 힘
Fsum = F1 + F2
magn, angle = get_mag_deg(Fsum)
print("결합한 힘의 크기 : ", magn)
print("결합한 힘의 방향 : ", angle)

결합한 힘의 크기 :  212.56671821060448
결합한 힘의 방향 :  46.395392948206855


## 6.2 다음 벡터 A, B 의 사잇각과, A 의 B 위로의 정사영을 구하라.

In [8]:
import numpy as np

def angle_to_vectors(v, w): # 두 벡터의 사잇각 계산
    vnorm = np.linalg.norm(v)
    wnorm = np.linalg.norm(w)
    vwdot = np.dot(v.T, w)
    angle = np.arctan(vwdot/(vnorm*wnorm))*360/np.pi
    return angle

def orth_proj(u, x): # 정사영 계산
    xu_dot = np.dot(x.T, u)
    uu_dot = np.dot(u.T, u)
    projux = (xu_dot/uu_dot)*u
    return projux

A = np.array([[2], [4], [1]])
B = np.array([[1], [-1], [3]])
angle = angle_to_vectors(A, B)
projAB = orth_proj(B, A)
print("A와 B의 사잇각 : ", angle)
print("A의 B 위로의 정사영 : \n", projAB)


A와 B의 사잇각 :  [[7.52871961]]
A의 B 위로의 정사영 : 
 [[ 0.09090909]
 [-0.09090909]
 [ 0.27272727]]


## 6.3 다음의 네 점 A, B, C, D 에 대해, 선분 $\overline{AB}$, $\overline{AC}$, $\overline{AD}$ 로 만들어지는 평행육면체의 부피를 구하라.

In [9]:
import numpy as np

def triple_product(u, v, w): # 스칼라 삼중적 u ․ (v × w) 계산
    M = np.zeros((3,3))
    M[0:] = u
    M[1:] = v
    M[2:] = w
    val = np.linalg.det(M) # 행벡터가 u, v, w인 행렬의 행렬식 계산
    return val

A = np.array([1, 2, 3])
B = np.array([0, 5, 2])
C = np.array([2, 2, 4])
D = np.array([2, 4, 1])
u = B-A
v = C-A
w = D-A
val = triple_product(u, v, w)
print("부피 : ", np.absolute(val))


부피 :  9.000000000000002


## 6.4 다음과 같은 점 A 를 포함하고 법선벡터가 W 인 평면과 점 P 사이의 거리를 계산하라(A=(2,3,4), W=(1,2,3), P=(0,1,2))

In [10]:
import numpy as np

def dist_pt_to_pl(A, W, P): # 거리 계산
    num = np.dot((P-A).T, W)
    deno = np.linalg.norm(W)
    val = np.absolute(num)/deno
    return val

A = np.array([2, 3, 4])
W = np.array([1, 2, 3])
P = np.array([0, 1, 2])
print("거리 : ", dist_pt_to_pl(A, W, P))


거리 :  3.2071349029490928
